name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'

jobs:
  tests-xcode-12_2:
    name: Test Builds - Xcode 12.2
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    
    steps:
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v2

      - name: ðŸ§± Build
        run: make build-release

      - name: ðŸš© Checkout Vexil
        uses: actions/checkout@v2
        with:
          repository: unsignedapps/Vexil
          ref: v1.2.2
          path: Vexil

      - name: ðŸ“¦ Package Vexil
        run: cd Vexil && ../.build/release/swift-create-xcframework --zip --zip-version 1.2.2 --platform ios --platform macos --platform tvos --platform watchos

  tests-xcode-12:
    name: Test Builds - Xcode 12
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    
    steps:
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v2

      - name: ðŸ§± Build
        run: make build-release

      - name: ðŸš© Checkout Vexil
        uses: actions/checkout@v2
        with:
          repository: unsignedapps/Vexil
          ref: v1.2.2
          path: Vexil

      - name: ðŸ“¦ Package Vexil
        run: cd Vexil && ../.build/release/swift-create-xcframework --zip --zip-version 1.2.2 --platform ios --platform macos --platform tvos --platform watchos
